Лабораторная работа 1
FedorovMisha/PlanetNews pull request #2
Opened 2021-11-30 12:39 UTC by FedorovMisha

2021-11-30 13:17 UTC, dkorkin requested changes
Минорные правки и с этим уже можно жить

2021-11-30 13:17 UTC, dkorkin commented on PlanetNews/PlanetNews/AppDelegate.swift
> +//        navigationController.setNavigationBarHidden(true, animated: false)
удаляем?

2021-11-30 13:17 UTC, dkorkin commented on PlanetNews/PlanetNews/ViewModels/SignUpViewModel.swift
> +        case .name:
нам точно нужен тут свитч?

2021-11-30 13:17 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/Shared/Cells/ContentViewCell.swift
> +        usingView = view
разбей по методам

2021-11-30 13:17 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/SignUp/SignUpViewController.swift
> +        let alertVc = UIAlertController(title: "Incorrect data", message: message, preferredStyle: .alert)
локализация строк

2021-11-30 13:17 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/TestViewController.swift
> +    // MARK: - Navigation
убираем?

2021-11-30 17:42 UTC, FedorovMisha commented on PlanetNews/PlanetNews/ViewModels/SignUpViewModel.swift
> +        case .name:
Да

2021-11-30 17:42 UTC, FedorovMisha commented on PlanetNews/PlanetNews/AppDelegate.swift
> +//        navigationController.setNavigationBarHidden(true, animated: false)
Нет
Забыл раскоментировать

2021-12-01 07:52 UTC, dkorkin approved these changes
Можно приходить на защиту, мелкие правки

2021-12-01 07:52 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/Shared/Cells/TextFieldViewCell.swift
> +    var didEditingChangeDelegate: ((String) -> Void)?
почему не просто делегат ячейки?

2021-12-01 07:52 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/Shared/Cells/TextFieldViewCell.swift
> +        selectionStyle = .none
там вынес в отдельный метод, тут нет(

2021-12-01 07:52 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/SignIn/SignInView.swift
> +    lazy var headerView: UIView = {
вынеси в отдельный класс

2021-12-01 07:52 UTC, dkorkin commented on PlanetNews/PlanetNews/Views/SignIn/SignInViewController.swift
> +        self.signInView.submitDelegate = self.didTouchSignInButton
не супер решения, но раз так, вынеси в отдельный метод всю конфигурацию

2021-12-03 18:06 UTC, merged